#!/bin/bash
# The shebang is just a hint for editors.

if [ "${_socks_cli}" = "1" ]; then
    function _restore_var() {
        if [ -n "$1" ]; then
            local VAR="_socks_cli_saved_$1"
            if _defined "${VAR}"; then
                echo "export $1=\"\${${VAR}}\"; unset ${VAR}"
            else
                # Check if the variable really exists, for security.
                # e.g. to avoid code injection or something else.
                _defined "$1" && echo "unset $1"
            fi
        fi
    }

    # Execute deactivation hooks
    for support in "${_socks_cli_supports[@]}"; do
        _hook="socks_cli_deactivate_$support"
        _is_function_exist "$_hook" && "$_hook"
    done

    # Restore variables
    for var in "${_socks_cli_saved_vars[@]}"; do
        eval "$(_restore_var $var)"
    done

    unset _socks_cli
fi
