#!/bin/bash
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${CURRENT_DIR}"
[ -f connect/connect ] || make -C connect
source socksproxyenv
./connect/connect -S ${SOCKS_PROXY} "$@"
