#!/bin/bash
# The shebang is just a hint for editors.

function socks_cli_activate_dsocks() {
    local _socks_cli_dsocks_lib="${SOCKS_CLI_DIR}/dsocks/libdsocks.so"
    "${SOCKS_CLI_DIR}/sh/bootstrap-dsocks.sh"
    if [ ! -f "${_socks_cli_dsocks_lib}" ]; then
        _logerror "Error: ${_socks_cli_dsocks_lib} isn't exist,"
        _logerror "       the SOCKSIFY feature will be disabled."
        return 1
    fi

    EXPORT_ENV DSOCKS_LIBRARY "${_socks_cli_dsocks_lib}"
    EXPORT_ENV DSOCKS_PROXY "${SOCKS_PROXY}"

    _socks_cli_socksify=1
}

function socks_cli_deactivate_dsocks() {
    unset _socks_cli_socksify
}

function SOCKSIFY() {
    if [ "${_socks_cli_socksify}" != "1" ]; then
        return 1
    fi
    if [ $# -lt 1 ]; then
        _logerror "Error: SOCKSIFY() requires at least one parameter."
        return 1
    fi

    local hook_command="$1"
    local start_command="${@:2}"
    if [ -z "$start_command" ]; then
        start_command="${hook_command}"
    fi
    SHADOW "${hook_command}" "${SOCKS_CLI_DIR}/dsocks/socksify" "${start_command}"
}
